name: Make Release
on:
  push:
    tags:
    - '*'

env:
  REPOSITORY_NAME: sigma_aviutl_scripts

  TIME_ZONE: Asia/Tokyo
  # Time zone for the timestamp when releasing.

permissions:
  contents: read

jobs:
  release:
    name: Create Release
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Pack and compress
      run: |
        mkdir pack
        cp *.anm pack
        cp *.obj pack
        cp *.scn pack
        cp *.lua pack
        cp -R exa pack/exa
        cp -R figure pack/figure
        cp Credits.md pack/Credits.md
        cp LICENSE pack/LICENSE
        cd pack
        zip -r ../${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.zip *
      # rename .zip file for downloading if necessary.

      - name: Pack README
      run: |
        mkdir pack2
        cp README.md pack2/README.md
        cp about_sigma_lib.md pack2/about_sigma_lib.md
        cp about_sigma_rot_helper.md pack2/about_sigma_rot_helper.md
        cp -R assets pack2/assets
        cd pack2
        zip -r ../README-${{ github.ref_name }}.zip *
      # rename .zip file for downloading if necessary.

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: 'v${{ github.ref_name }}'
        files: '*.zip'
        draft: true
        body: THIS IS A DRAFT MESSAGE.
